### ISSUE TITLE
Index Registration Service

### ISSUE THREAD

**Issue by Teanchupong** [TN-INCORPORATION/TXN_Transaction#1]
As the TXN Domain, If a customer want to do financial transaction to a bank account. System should register account number for a customer before do financial transaction. So after account is created in Account Domain, the system will automatically register account number for the customer to support financial transaction.

Acceptance Criteria:
• System will register account automatically after received the API - Account Registration Message.
• System will register account number with 12 digits same as the index number in the API message.
• System will register account number with currency same as the currency in the API message.

Message on Features:

No.|Description|Message Pop Up
----|------------|-------------------
1|Header Error	|"Please verify Header Message"
2|Index No. Error|"Invalid Index No."
3|Currency Error|"Invalid Currency Code"
4|Duplicated Index No.|"Duplicated Index No."
5|Registration Completed|"Registration Completed"
6|Failed Registration|"Can not register account"

Test Cases:

No.|Test Cases	|Test Result
----|------------|------------
1|Receive message with Index No. equal 12 digits.|System able to register account number.
2|Receive message with Index No. less than 12 digits.|System unable to register account number. Return "Invalid Index No."
3|Receive message with Index No. more than 12 digits.|System unable to register account number. Return "Invalid Index No."
4|Receive message with Index No. is empty.|System unable to register account number. Return "Invalid Index No."
5|Receive message with Index No. is character.|System unable to register account number. Return "Invalid Index No."
6|Receive message with duplicated Index No.|System unable to register account number. Return "Duplicated Index No."
7|Receive message with invalid currency code|System unable to register account number. Return "Invalid Currency Code"

Acceptance Tests :

No.|Given|When|Then
----|------|-------|-----
1|Register an account number with Index No. is equal to 12 digits.|Receive message from Account Domain with Index No. is equal to 12 digits. AND create account.(Index no = 123456789012)|The system is able to regiter an account number. AND return "Registration Completed"
2|Register an account number with Index No. less than 12 digits.|Receive message from Account Domain with Index No. less than 12 digits. AND create account.(Index no = 12345678901)|The System is unable to register an account number AND return "Invalid Index No."
3|Register an account number with Index No. more than 12 digits.|Receive message from Account Domain with Index No. more than 12 digits. AND create account.(Index no = 1234567890123)|The System is unable to register an account number AND return "Invalid Index No."
4|Register an account number with Index No. is empty.|Receive message from Account Domain with Index No. is empty. AND create account. (Index no = '')|The System is unable to register an account number AND return "Invalid Index No."
5|Register an account number with Index No. is character.|Receive message from Account Domain with Index No. is character. AND create account. (Index no = abc)|The System is unable to register an account number AND return "Invalid Index No."
6|Register an account number with duplicated Index No.|Receive message from Account Domain with duplicated Index No. AND create account. (Index no = 123456789012)|The System is unable to register an account number AND return "Duplicated Index No."
7|Register an account number with invalid currency|Receive message from Account Domain with invalid currency. AND create account. (Currency = XYZ)|The System is unable to register an account number AND return "Invalid Currency Code."

**Comment by thanaphan-wo** [comment]
**Unit test result**
[UnitTest_Result_IndexRegistrationService.zip](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1077123/UnitTest_Result_IndexRegistrationService.zip)

**Comment by santisuk-ji** [comment]
API document

[API document.xlsx](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1077286/API.document.xlsx)

**Comment by santisuk-ji** [comment]
test result (service section)

total case : 8
pass : 8
code coverage : 84.7%

result is attach in picture below

![sprint 1 test result](https://user-images.githubusercontent.com/29219697/27177295-0abbd8c2-51f0-11e7-91aa-be160796da0a.png)

**Comment by Pawarit-ki** [comment]
Technical Specification
[TechSpec_Spin1_PBI1_TXN Account Registration Service.docx](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1077401/TechSpec_Spin1_PBI1_TXN.Account.Registration.Service.docx)

**Comment by Patthara-th** [comment]
[Data Dic & Config_v0.01.xlsx](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1077532/Data.Dic.Config_v0.01.xlsx)


[Database Diagram_v0.02.pdf](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1077534/Database.Diagram_v0.02.pdf)
