### ISSUE TITLE
PSL Coding Standard for automate testing framework

### ISSUE THREAD

**Issue by Teanchupong** [TN-INCORPORATION/TXN_Transaction#2]
As a development team, I want to update "Profile CBS Database and coding Standard" to comply with  automated build/testing framework (CI). 

No.|Topic
----|-------
1| Standard for coding unit test script.
2|Standard for logging test result.
3|Standard for logging code coverage.

Acceptance Criteria:
• Developer can use this coding standard to develop software that can be test in automated testing framework and can measure the code quality transparently.

**Comment by thanaphan-wo** [comment]
**Profile CBS Database Standard and Coding Standard**
[https://github.com/TN-INCORPORATION/development-documentation/blob/master/PSL_Programing-Standard.md](url)
