### ISSUE TITLE
Extended length of transaction amount and balances

### ISSUE THREAD

**Issue by Teanchupong** [TN-INCORPORATION/TXN_Transaction#6]
According to IDR currency, TXN Domain have to extend length of transaction amount and account balance to 25 digits and 2 decimals for supporting transaction in IDR currency.

Detail :

Field|Layout
-----|--------
Transaction Amount|XXXXXXXXXXXXXXXXXXXXXX.XX
Account Balance|XXXXXXXXXXXXXXXXXXXXXX.XX

Acceptance Criteria :

- System will support the transaction service with transaction amount within 25 digits and 2 decimals.

- System will support the account balance after transaction posted within 25 digits and 2 decimals.

- System will support the inquiry transaction in account balance within 25 digits and 2 decimals.

**Comment by Teanchupong** [comment]
**Test Cases**
[Sprint#3_Test Case.xlsx](https://github.com/TN-INCORPORATION/TXN_Transaction/files/1114900/Sprint.3_Test.Case.xlsx)

**Comment by thanaphan-wo** [comment]
**Test Result (Balance Inquiry Service)**
Add 2 test case
- account balance equal 18 digits (positive balance)
- account balance equal 18 digits (negative balance)

total case : 5
pass : 5
code coverage : 72.3%

result is attach in picture below
![image](https://user-images.githubusercontent.com/29172949/27951815-677acd06-6330-11e7-9817-a4a9d47be605.png)
